// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9GgfV_p1-Prp8Ey-9NjogXtPccZ8pB-E',
    appId: '1:532045092431:web:4ea5929c60ddd6be847c3a',
    messagingSenderId: '532045092431',
    projectId: 'falconx-41506',
    authDomain: 'falconx-41506.firebaseapp.com',
    databaseURL: 'https://falconx-41506-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'falconx-41506.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc3ZVMxzwInjIV7zKyM4XPPMN_DFR4Ek0',
    appId: '1:532045092431:android:84e7ebf9b42d0e0c847c3a',
    messagingSenderId: '532045092431',
    projectId: 'falconx-41506',
    databaseURL: 'https://falconx-41506-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'falconx-41506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKDkT9l6Y5CMnkvZ9Shf619cNSYFplyWk',
    appId: '1:532045092431:ios:12d1baba274eaa88847c3a',
    messagingSenderId: '532045092431',
    projectId: 'falconx-41506',
    databaseURL: 'https://falconx-41506-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'falconx-41506.appspot.com',
    iosClientId: '532045092431-j21vjvrm6ftrhqauudh8fpa3uj41eg50.apps.googleusercontent.com',
    iosBundleId: 'com.existing.flutter.falconx.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKDkT9l6Y5CMnkvZ9Shf619cNSYFplyWk',
    appId: '1:532045092431:ios:e7f58220e1a01dee847c3a',
    messagingSenderId: '532045092431',
    projectId: 'falconx-41506',
    databaseURL: 'https://falconx-41506-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'falconx-41506.appspot.com',
    iosClientId: '532045092431-n7lcc0cjolma75pnji2kg5l8r7dn9fut.apps.googleusercontent.com',
    iosBundleId: 'com.existing.flutter.falconx',
  );
}
